// ---------------------------------------------------------------------------------------------------------
// Copyright 2020 Viniciusalopes Tecnologia <suporte@viniciusalopes.com.br>
// Licença      : MIT <https://opensource.org/licenses/MIT> 
// Data         : 22/02/2020
// Projeto      : POO - Lista de Exercícios 1 
// Repositório  : <https://github.com/Viniciusalopes/ads20192-modulo2/tree/master/poo/lista-de-exercicios-1>
// ---------------------------------------------------------------------------------------------------------

package gui;

import classes.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author vovo
 */
public class Tela extends javax.swing.JFrame {

    Funcionario oreiaSeca = new Funcionario();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(375, this.getSize().height);
        estadoInicialDosComponentes();
    }

    private void estadoInicialDosComponentes() {
        jTextFieldNome.setText("");
        jTextFieldNome.setEnabled(true);
        jTextFieldSalario.setText("");
        jTextFieldSalario.setEnabled(true);
        jTextFieldFilhos.setText("");
        jTextFieldFilhos.setEnabled(true);

        jButtonCalcularInssIr.setVisible(true);
        jButtonAumentoDeSalario.setVisible(false);
        jButtonNovoFuncionario.setVisible(false);

        jPanelSaida.setVisible(false);
        jPanelAumento.setVisible(false);

        jTextFieldNome.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCampos = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSalario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFilhos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelBotoes = new javax.swing.JPanel();
        jButtonAumentoDeSalario = new javax.swing.JButton();
        jButtonCalcularInssIr = new javax.swing.JButton();
        jButtonNovoFuncionario = new javax.swing.JButton();
        jPanelSaida = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSaida = new javax.swing.JTextArea();
        jPanelAumento = new javax.swing.JPanel();
        jLabelPercent = new javax.swing.JLabel();
        jTextFieldPercentual = new javax.swing.JTextField();
        jButtonCalcularAumento = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Funcionário");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel2.setText("Salário");

        jLabel3.setText("Quantidade de Filhos");

        javax.swing.GroupLayout jPanelCamposLayout = new javax.swing.GroupLayout(jPanelCampos);
        jPanelCampos.setLayout(jPanelCamposLayout);
        jPanelCamposLayout.setHorizontalGroup(
            jPanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamposLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanelCamposLayout.createSequentialGroup()
                        .addGroup(jPanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCamposLayout.setVerticalGroup(
            jPanelCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonAumentoDeSalario.setText("Aumento de Salário");
        jButtonAumentoDeSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentoDeSalarioActionPerformed(evt);
            }
        });

        jButtonCalcularInssIr.setText("Calcular INSS e IR");
        jButtonCalcularInssIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularInssIrActionPerformed(evt);
            }
        });

        jButtonNovoFuncionario.setText("Novo Funcionário");
        jButtonNovoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLayout = new javax.swing.GroupLayout(jPanelBotoes);
        jPanelBotoes.setLayout(jPanelBotoesLayout);
        jPanelBotoesLayout.setHorizontalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonCalcularInssIr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAumentoDeSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovoFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBotoesLayout.setVerticalGroup(
            jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotoesLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcularInssIr)
                    .addComponent(jButtonAumentoDeSalario)
                    .addComponent(jButtonNovoFuncionario)))
        );

        jLabel4.setText("Saída");

        jTextAreaSaida.setEditable(false);
        jTextAreaSaida.setColumns(20);
        jTextAreaSaida.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSaida);

        javax.swing.GroupLayout jPanelSaidaLayout = new javax.swing.GroupLayout(jPanelSaida);
        jPanelSaida.setLayout(jPanelSaidaLayout);
        jPanelSaidaLayout.setHorizontalGroup(
            jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaidaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSaidaLayout.setVerticalGroup(
            jPanelSaidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSaidaLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabelPercent.setText("Percentual de aumento");

        jButtonCalcularAumento.setText("Calcular Salário");
        jButtonCalcularAumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularAumentoActionPerformed(evt);
            }
        });

        jLabel5.setText("%");

        javax.swing.GroupLayout jPanelAumentoLayout = new javax.swing.GroupLayout(jPanelAumento);
        jPanelAumento.setLayout(jPanelAumentoLayout);
        jPanelAumentoLayout.setHorizontalGroup(
            jPanelAumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAumentoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelAumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPercent)
                    .addComponent(jButtonCalcularAumento)
                    .addGroup(jPanelAumentoLayout.createSequentialGroup()
                        .addComponent(jTextFieldPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelAumentoLayout.setVerticalGroup(
            jPanelAumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPercent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonCalcularAumento)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelAumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanelCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCalcularInssIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularInssIrActionPerformed
        try {
            oreiaSeca.setNome(jTextFieldNome.getText());
            oreiaSeca.setSalario(Float.parseFloat(jTextFieldSalario.getText()));
            oreiaSeca.setFilhos(Integer.parseInt(jTextFieldFilhos.getText()));

            jTextAreaSaida.setText(String.format(
                    "DADOS DO FUNCIONÁRIO:\n"
                    + "Nome: %s\n"
                    + "Salário: R$ %.2f\n"
                    + "Filho(s): %d\n\n"
                    + "CÁLCULOS:\n"
                    + "INSS: R$ %.2f (%.2f %%)\n"
                    + "Parcela IR: R$ %.2f (%.2f %%)\n"
                    + "Valor Mensal IR: R$ %.2f",
                    oreiaSeca.getNome(),
                    oreiaSeca.getSalario(),
                    oreiaSeca.getFilhos(),
                    oreiaSeca.getInssValor(), oreiaSeca.getInssAliquota(),
                    oreiaSeca.getIrParcela(), oreiaSeca.getIrAliquota(),
                    oreiaSeca.getIrValorMensal()
            ));
            jTextFieldNome.setEnabled(false);
            jTextFieldSalario.setEnabled(false);
            jTextFieldFilhos.setEnabled(false);

            jButtonCalcularInssIr.setVisible(false);
            jButtonAumentoDeSalario.setVisible(true);
            jButtonNovoFuncionario.setVisible(true);
            jPanelSaida.setVisible(true);
            jTextAreaSaida.grabFocus();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCalcularInssIrActionPerformed

    private void jButtonAumentoDeSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentoDeSalarioActionPerformed

        jPanelBotoes.setVisible(false);
        jPanelSaida.setVisible(false);
        jPanelAumento.setVisible(true);
        jTextFieldPercentual.setText("");
        jTextFieldPercentual.grabFocus();
    }//GEN-LAST:event_jButtonAumentoDeSalarioActionPerformed

    private void jButtonCalcularAumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularAumentoActionPerformed
        try {
            float salarioAnterior = oreiaSeca.getSalario();
            float percent = Float.parseFloat(jTextFieldPercentual.getText());
            float aumento = oreiaSeca.getAumentoSalarial(percent);
            float novoSalario = salarioAnterior + aumento;
            oreiaSeca.setSalario(novoSalario);
            jTextFieldSalario.setText("" + oreiaSeca.getSalario());

            jTextAreaSaida.setText(String.format(
                    "DADOS DO FUNCIONÁRIO:\n"
                    + "Nome: %s\n"
                    + "Salário Anterior: R$ %.2f\n"
                    + "Aumento: R$ %.2f (%.2f %%)\n"
                    + "Salário Atual: R$ %.2f\n"
                    + "Filho(s): %d\n\n"
                    + "CÁLCULOS:\n"
                    + "INSS: R$ %.2f (%.2f %%)\n"
                    + "Parcela IR: R$ %.2f (%.2f %%)\n"
                    + "Valor Mensal IR: R$ %.2f",
                    oreiaSeca.getNome(),
                    salarioAnterior,
                    aumento, percent,
                    oreiaSeca.getSalario(),
                    oreiaSeca.getFilhos(),
                    oreiaSeca.getInssValor(), oreiaSeca.getInssAliquota(),
                    oreiaSeca.getIrParcela(), oreiaSeca.getIrAliquota(),
                    oreiaSeca.getIrValorMensal()
            ));

            jButtonCalcularInssIr.setVisible(false);
            jButtonAumentoDeSalario.setVisible(true);
            jPanelBotoes.setVisible(true);
            jPanelAumento.setVisible(false);
            jPanelSaida.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCalcularAumentoActionPerformed

    private void jButtonNovoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFuncionarioActionPerformed
        estadoInicialDosComponentes();
    }//GEN-LAST:event_jButtonNovoFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAumentoDeSalario;
    private javax.swing.JButton jButtonCalcularAumento;
    private javax.swing.JButton jButtonCalcularInssIr;
    private javax.swing.JButton jButtonNovoFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPercent;
    private javax.swing.JPanel jPanelAumento;
    private javax.swing.JPanel jPanelBotoes;
    private javax.swing.JPanel jPanelCampos;
    private javax.swing.JPanel jPanelSaida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaSaida;
    private javax.swing.JTextField jTextFieldFilhos;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPercentual;
    private javax.swing.JTextField jTextFieldSalario;
    // End of variables declaration//GEN-END:variables
}
